"""IR (Intermediate Representation) models for NL2Data."""

from .requirement import RequirementIR, ScaleHint, DistributionHint
from .conceptual import ConceptualIR, Entity, Attribute, Relationship
from .logical import LogicalIR, TableSpec, ColumnSpec, ForeignKeySpec
from .generation import (
    GenerationIR,
    ColumnGenSpec,
    ProviderRef,
    Distribution,
    DistUniform,
    DistNormal,
    DistLognormal,
    DistPareto,
    DistPoisson,
    DistExponential,
    DistMixture,
    DistMixtureComponent,
    DistZipf,
    DistSeasonal,
    DistCategorical,
    DistDerived,
    DistWindow,
    WindowFrame,
    CategoricalDomain,
    EventSpec,
    EventEffect,
)
from .workload import WorkloadIR, WorkloadSpec
from .dataset import DatasetIR
from .constraint_ir import (
    ConstraintSpec,
    FDConstraint,
    ImplicationConstraint,
    CompositePKConstraint,
    ConditionExpr,
    AtomicCondition,
)
from .validators import QaIssue, DatasetQaIssue

__all__ = [
    "RequirementIR",
    "ScaleHint",
    "DistributionHint",
    "ConceptualIR",
    "Entity",
    "Attribute",
    "Relationship",
    "LogicalIR",
    "TableSpec",
    "ColumnSpec",
    "ForeignKeySpec",
    "GenerationIR",
    "ColumnGenSpec",
    "ProviderRef",
    "Distribution",
    "DistUniform",
    "DistNormal",
    "DistLognormal",
    "DistPareto",
    "DistPoisson",
    "DistExponential",
    "DistMixture",
    "DistMixtureComponent",
    "DistZipf",
    "DistSeasonal",
    "DistCategorical",
    "DistDerived",
    "DistWindow",
    "WindowFrame",
    "CategoricalDomain",
    "EventSpec",
    "EventEffect",
    "WorkloadIR",
    "WorkloadSpec",
    "DatasetIR",
    "ConstraintSpec",
    "FDConstraint",
    "ImplicationConstraint",
    "CompositePKConstraint",
    "ConditionExpr",
    "AtomicCondition",
    "QaIssue",
    "DatasetQaIssue",
]

